export const DEFAULT_RESEARCH_PILGER_TOPICS = [
    {
        id: 'bc-luxo',
        topic: 'Balneario Camboriu imoveis de luxo',
        region: 'Balneario Camboriu, SC',
        intent: 'blog',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'barra-sul-frente-mar',
        topic: 'Barra Sul frente mar valorizacao imobiliaria',
        region: 'Barra Sul, Balneario Camboriu, SC',
        intent: 'mercado',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'praia-brava-valorizacao',
        topic: 'Praia Brava Itajai valorizacao imoveis alto padrao',
        region: 'Praia Brava, Itajai, SC',
        intent: 'trafego',
        priority: 'media',
        frequency: 'quinzenal',
        status: 'ativo',
    },
    {
        id: 'litoral-sc-investimento',
        topic: 'investimento imobiliario litoral de Santa Catarina',
        region: 'Litoral SC',
        intent: 'ceo',
        priority: 'media',
        frequency: 'mensal',
        status: 'ativo',
    },
    {
        id: 'bc-metro-quadrado',
        topic: 'preco do metro quadrado em Balneario Camboriu alto padrao',
        region: 'Balneario Camboriu, SC',
        intent: 'mercado',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'barra-norte-vs-barra-sul',
        topic: 'Barra Norte ou Barra Sul qual regiao e melhor para investir',
        region: 'Balneario Camboriu, SC',
        intent: 'blog',
        priority: 'alta',
        frequency: 'quinzenal',
        status: 'ativo',
    },
    {
        id: 'frente-mar-liquidez',
        topic: 'imovel frente mar tem mais liquidez em Balneario Camboriu',
        region: 'Balneario Camboriu, SC',
        intent: 'blog',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'itajai-vs-bc',
        topic: 'Itajai ou Balneario Camboriu onde comprar imovel de alto padrao',
        region: 'Itajai e Balneario Camboriu, SC',
        intent: 'blog',
        priority: 'media',
        frequency: 'quinzenal',
        status: 'ativo',
    },
    {
        id: 'investidor-alto-padrao',
        topic: 'perfil do comprador de imovel de luxo no litoral catarinense',
        region: 'Litoral de Santa Catarina',
        intent: 'ceo',
        priority: 'media',
        frequency: 'mensal',
        status: 'ativo',
    },
    {
        id: 'google-ads-imoveis-luxo',
        topic: 'termos de busca para Google Ads imoveis de luxo Balneario Camboriu',
        region: 'Balneario Camboriu, SC',
        intent: 'trafego',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'seo-aeo-bc',
        topic: 'perguntas frequentes sobre comprar imovel em Balneario Camboriu',
        region: 'Balneario Camboriu, SC',
        intent: 'blog',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'estoque-coberturas',
        topic: 'demanda por coberturas duplex em Balneario Camboriu',
        region: 'Balneario Camboriu, SC',
        intent: 'estoque',
        priority: 'media',
        frequency: 'quinzenal',
        status: 'ativo',
    },
    {
        id: 'noticias-bc-prefeitura',
        topic: 'noticias da prefeitura de Balneario Camboriu obras turismo mobilidade e urbanismo',
        region: 'Balneario Camboriu, SC',
        intent: 'prefeitura',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'noticias-itapema-prefeitura',
        topic: 'noticias da prefeitura de Itapema obras turismo infraestrutura e mercado imobiliario',
        region: 'Itapema, SC',
        intent: 'prefeitura',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'noticias-porto-belo-prefeitura',
        topic: 'noticias da prefeitura de Porto Belo Pereque obras turismo e desenvolvimento urbano',
        region: 'Porto Belo, SC',
        intent: 'prefeitura',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'noticias-itajai-praia-brava',
        topic: 'noticias de Itajai Praia Brava obras mobilidade turismo nautico e valorizacao imobiliaria',
        region: 'Itajai e Praia Brava, SC',
        intent: 'noticias',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'economia-imobiliaria-sc',
        topic: 'noticias de economia imobiliaria em Santa Catarina juros credito construcao civil e mercado de luxo',
        region: 'Santa Catarina',
        intent: 'economia',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'cidades-empreendimentos-pilger',
        topic: 'melhores cidades para investir em imoveis de alto padrao no litoral norte de Santa Catarina',
        region: 'Balneario Camboriu, Itapema, Itajai, Porto Belo',
        intent: 'empreendimentos',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'turismo-eventos-bc-mercado',
        topic: 'eventos turismo e ocupacao hoteleira em Balneario Camboriu impacto no mercado imobiliario',
        region: 'Balneario Camboriu, SC',
        intent: 'noticias',
        priority: 'media',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'infraestrutura-navegantes-itajai',
        topic: 'aeroporto de Navegantes porto de Itajai marina mobilidade e impacto no mercado imobiliario',
        region: 'Itajai, Navegantes, Praia Brava, SC',
        intent: 'economia',
        priority: 'media',
        frequency: 'quinzenal',
        status: 'ativo',
    },
    {
        id: 'novos-empreendimentos-litoral-norte',
        topic: 'novos empreendimentos de luxo no litoral norte de Santa Catarina Balneario Camboriu Itapema Praia Brava Porto Belo',
        region: 'Litoral Norte de Santa Catarina',
        intent: 'empreendimentos',
        priority: 'alta',
        frequency: 'semanal',
        status: 'ativo',
    },
    {
        id: 'construcao-civil-sc-luxo',
        topic: 'noticias da construcao civil em Santa Catarina mercado de alto padrao e incorporadoras',
        region: 'Santa Catarina',
        intent: 'economia',
        priority: 'media',
        frequency: 'semanal',
        status: 'ativo',
    },
]

export function getDefaultResearchPilgerTopicsJson() {
    return JSON.stringify(DEFAULT_RESEARCH_PILGER_TOPICS)
}
