-- Migration: Pilger AI Engine (Cloner + Concierge)
-- Description: Adds tables for AI Landing Pages and extends Leads table for Concierge data.

-- 1. Create Landing Pages Table
create type landing_page_status as enum ('draft', 'queued', 'processing', 'completed', 'failed');

create table if not exists public.landing_pages (
    id uuid not null default gen_random_uuid(),
    slug text not null unique,
    original_url text,
    custom_prompt text,
    title text,
    description text,
    content jsonb, -- Structured content generated by Gemini
    status landing_page_status default 'draft',
    property_id uuid references public.properties(id) on delete set null,
    metadata jsonb default '{}'::jsonb, -- Store extra info like source R2 keys
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    primary key (id)
);

-- Enable RLS for Landing Pages
alter table public.landing_pages enable row level security;

-- Policies for Landing Pages
create policy "Public Read Access" on public.landing_pages
    for select using (true);

create policy "Admin Full Access" on public.landing_pages
    for all using (auth.role() = 'authenticated'); -- Assuming authenticated users are admins for now

-- 2. Extend Leads Table for Concierge AI
-- Check if columns exist before creating generally requires dynamic SQL in Postgres 
-- or just robust 'add column if not exists' (Postgres 9.6+ supports if not exists on create table, not alter column easily without do block)

do $$ 
begin 
    if not exists (select 1 from information_schema.columns where table_name = 'leads' and column_name = 'budget') then
        alter table public.leads add column budget text;
    end if;

    if not exists (select 1 from information_schema.columns where table_name = 'leads' and column_name = 'timeframe') then
        alter table public.leads add column timeframe text;
    end if;

    if not exists (select 1 from information_schema.columns where table_name = 'leads' and column_name = 'conversation_log') then
        alter table public.leads add column conversation_log jsonb default '[]'::jsonb;
    end if;

    if not exists (select 1 from information_schema.columns where table_name = 'leads' and column_name = 'landing_page_id') then
        alter table public.leads add column landing_page_id uuid references public.landing_pages(id) on delete set null;
    end if;
    
    if not exists (select 1 from information_schema.columns where table_name = 'leads' and column_name = 'ai_summary') then
        alter table public.leads add column ai_summary text;
    end if;
end $$;

-- 3. Create Indexes
create index if not exists idx_landing_pages_slug on public.landing_pages(slug);
create index if not exists idx_leads_landing_page on public.leads(landing_page_id);
