INSERT INTO public.message_templates (
  template_key,
  business_unit,
  channel,
  event_type,
  name,
  subject,
  body,
  variables,
  requires_opt_in,
  is_active,
  metadata
)
VALUES
  (
    'checkout_payment_processing',
    'education',
    'whatsapp',
    'payment.processing',
    'Pagamento em processamento',
    NULL,
    'Oi {nome}, recebemos a tentativa de pagamento do {produto}, mas ela ainda esta em analise. Assim que for aprovada, liberamos seu acesso automaticamente.',
    '["nome","produto"]'::jsonb,
    true,
    true,
    '{"sender_agent":"whatsapp-global-agent"}'::jsonb
  ),
  (
    'checkout_payment_processing_email',
    'education',
    'email',
    'payment.processing',
    'E-mail de pagamento em processamento',
    'Seu pagamento para {produto} esta em analise',
    'Ola, {nome}. Seu pedido {numero_pedido} para acessar {produto} esta em processamento. Avisaremos quando a aprovacao for confirmada.',
    '["nome","produto","numero_pedido"]'::jsonb,
    false,
    true,
    '{"sender_agent":"brevo-email"}'::jsonb
  ),
  (
    'checkout_payment_rejected',
    'education',
    'whatsapp',
    'payment.rejected',
    'Pagamento recusado',
    NULL,
    'Oi {nome}, o pagamento do {produto} foi recusado. Voce pode tentar novamente com Pix ou outro meio por aqui: {checkout_url}',
    '["nome","produto","checkout_url"]'::jsonb,
    true,
    true,
    '{"sender_agent":"whatsapp-global-agent"}'::jsonb
  ),
  (
    'checkout_payment_rejected_email',
    'education',
    'email',
    'payment.rejected',
    'E-mail de pagamento recusado',
    'Nao conseguimos aprovar seu pagamento',
    'Ola, {nome}. O pagamento do pedido {numero_pedido} para {produto} foi recusado. Para tentar novamente, acesse: {checkout_url}',
    '["nome","produto","numero_pedido","checkout_url"]'::jsonb,
    false,
    true,
    '{"sender_agent":"brevo-email"}'::jsonb
  ),
  (
    'checkout_payment_cancelled',
    'education',
    'whatsapp',
    'payment.cancelled',
    'Pagamento cancelado',
    NULL,
    'Oi {nome}, esse pagamento do {produto} foi cancelado. Se quiser continuar, gere um novo pagamento com seguranca por aqui: {checkout_url}',
    '["nome","produto","checkout_url"]'::jsonb,
    true,
    true,
    '{"sender_agent":"whatsapp-global-agent"}'::jsonb
  ),
  (
    'checkout_payment_cancelled_email',
    'education',
    'email',
    'payment.cancelled',
    'E-mail de pagamento cancelado',
    'Seu pagamento foi cancelado',
    'Ola, {nome}. O pagamento do pedido {numero_pedido} foi cancelado. Para continuar a compra de {produto}, acesse: {checkout_url}',
    '["nome","produto","numero_pedido","checkout_url"]'::jsonb,
    false,
    true,
    '{"sender_agent":"brevo-email"}'::jsonb
  ),
  (
    'checkout_payment_refunded',
    'education',
    'whatsapp',
    'payment.refunded',
    'Pagamento reembolsado',
    NULL,
    'Oi {nome}, o pagamento do {produto} foi marcado como reembolsado. Se precisar de ajuda, responda esta mensagem.',
    '["nome","produto"]'::jsonb,
    true,
    true,
    '{"sender_agent":"whatsapp-global-agent"}'::jsonb
  ),
  (
    'checkout_payment_refunded_email',
    'education',
    'email',
    'payment.refunded',
    'E-mail de pagamento reembolsado',
    'Pagamento reembolsado',
    'Ola, {nome}. O pagamento do pedido {numero_pedido} para {produto} foi marcado como reembolsado. Se precisar de suporte, responda este e-mail.',
    '["nome","produto","numero_pedido"]'::jsonb,
    false,
    true,
    '{"sender_agent":"brevo-email"}'::jsonb
  ),
  (
    'checkout_payment_chargeback',
    'education',
    'whatsapp',
    'payment.chargeback',
    'Pagamento contestado',
    NULL,
    'Oi {nome}, o pagamento do {produto} foi contestado no Mercado Pago. Nossa equipe vai revisar seu acesso. Se foi engano, responda esta mensagem para suporte.',
    '["nome","produto"]'::jsonb,
    false,
    true,
    '{"sender_agent":"whatsapp-global-agent"}'::jsonb
  ),
  (
    'checkout_payment_chargeback_email',
    'education',
    'email',
    'payment.chargeback',
    'E-mail de pagamento contestado',
    'Pagamento contestado',
    'Ola, {nome}. O pagamento do pedido {numero_pedido} para {produto} foi marcado como contestado. Nossa equipe vai revisar o acesso.',
    '["nome","produto","numero_pedido"]'::jsonb,
    false,
    true,
    '{"sender_agent":"brevo-email"}'::jsonb
  )
ON CONFLICT (business_unit, channel, template_key) DO UPDATE SET
  event_type = EXCLUDED.event_type,
  name = EXCLUDED.name,
  subject = EXCLUDED.subject,
  body = EXCLUDED.body,
  variables = EXCLUDED.variables,
  requires_opt_in = EXCLUDED.requires_opt_in,
  is_active = EXCLUDED.is_active,
  metadata = public.message_templates.metadata || EXCLUDED.metadata,
  updated_at = now();
